"""create core tables

Revision ID: 6425c7748f43
Revises: 
Create Date: 2026-02-15 13:55:47.226421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6425c7748f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('planner', 'designer', 'dev', 'tester', 'other', name='role_enum'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='level_enum'), nullable=False),
    sa.Column('goal', sa.Enum('concept', 'practice', 'assignment', 'interview', 'other', name='goal_enum'), nullable=False),
    sa.Column('stack', sa.String(length=200), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('context_id')
    )
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('data_range_json', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('users_anon',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('planner', 'designer', 'dev', 'tester', 'other', name='role_enum'), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='level_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('models',
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('model_version')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.Enum('controlled', 'free', name='question_type_enum'), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('question_text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.context_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_anon.user_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('answer_hash', sa.String(length=64), nullable=False),
    sa.Column('answer_summary', sa.Text(), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('len_words', sa.Integer(), nullable=False),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('step_score', sa.Integer(), nullable=False),
    sa.Column('has_bullets', sa.Boolean(), nullable=False),
    sa.Column('has_warning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('feedback_pairwise',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('candidate_a_id', sa.UUID(), nullable=False),
    sa.Column('candidate_b_id', sa.UUID(), nullable=False),
    sa.Column('user_choice', sa.Enum('a', 'b', 'tie', 'bad', name='pairwise_choice_enum'), nullable=False),
    sa.Column('reason_tags', postgresql.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_a_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['candidate_b_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('selections',
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('rule_choice_candidate_id', sa.UUID(), nullable=True),
    sa.Column('ltr_choice_candidate_id', sa.UUID(), nullable=True),
    sa.Column('served_choice_candidate_id', sa.UUID(), nullable=False),
    sa.Column('served_policy', sa.Enum('single_llm_openai', 'single_llm_gemini', 'rule', 'ltr', name='served_policy_enum'), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ltr_choice_candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['rule_choice_candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['served_choice_candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('selection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selections')
    op.drop_table('feedback_pairwise')
    op.drop_table('candidates')
    op.drop_table('questions')
    op.drop_table('models')
    op.drop_table('users_anon')
    op.drop_table('snapshots')
    op.drop_table('contexts')
    # ### end Alembic commands ###
